#!/usr/bin/env python
#
# Usage: mean_hr <LOGFILE>
#
# Parse a log file containing ANT+ data points from a heart rate
# monitor, and print out the heart rate averaged over the period
# of the log file.

from njcant.log_parser import parse_loglines
from njcant.event_timer import add_realtimes_to_datapoint_list
from njcant.hr_analysis import compute_mean_hr_bpm
from njcant.hrm_device import HrmDataPoint

def main(log_filename):
	hrm_data_points = [p for p in parse_loglines(open(log_filename)) if isinstance(p, HrmDataPoint)]
	add_realtimes_to_datapoint_list(hrm_data_points)
	mean_hr = compute_mean_hr_bpm(hrm_data_points)
	print "Mean HR: %f bpm" % mean_hr

if __name__ == '__main__':
	import sys
	main(sys.argv[1])

